# Generated by Django 4.1 on 2022-08-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
    ]
